require:
  - rubocop-rails
  - ./lib/rubocop/init_autoloader

AllCops:
  TargetRubyVersion: 3.3.0
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "bin/**/*"
###################
#   Custom Cops   #
###################
Custom/PrivateMethodStyle:
  Enabled: true
  AutoCorrect: true
###################
# End Custom Cops #
###################
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/IndentationWidth:
  Enabled: true
  Width: 2
Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
Lint/UnusedMethodArgument:
  AutoCorrect: false
Metrics/AbcSize:
  Exclude:
    - "app/models/application_record.rb"
Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
    - "lib/rubocop/cop/custom/*.rb"
Metrics/CyclomaticComplexity:
  Exclude:
    - "lib/rubocop/cop/custom/*.rb"
Metrics/MethodLength:
  Exclude:
    - "lib/rubocop/cop/custom/*.rb"
    - "app/models/application_record.rb"
Metrics/PerceivedComplexity:
  Exclude:
    - "lib/rubocop/cop/custom/*.rb"
Naming/VariableNumber:
  EnforcedStyle: snake_case
Rails/InverseOf:
  Enabled: false
Rails/UniqueValidationWithoutIndex:
  Description: "We will enforce this via PR review. This gives false positives at the moment."
  Details: "https://github.com/rubocop/rubocop-rails/issues/221"
  Enabled: true
  Severity: warning
Style/AccessModifierDeclarations:
  EnforcedStyle: inline
Style/Documentation:
  Enabled: false
Style/Lambda:
  EnforcedStyle: literal
Style/RedundantArgument:
  AutoCorrect: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
