branch-defaults:
  actions:
    environment: prod-env
  main:
    environment: prod-env
environment-defaults:
  prod-env:
    branch: null
    repository: null
global:
  application_name: hop-skip-drive-test
  default_ec2_keyname: null
  default_platform: Ruby 3.2 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
