# rubocop/action.yaml

name: "RuboCop"
description: "Run RuboCop checks on a Ruby project"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.2.0"

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
      shell: bash

    - name: Run RuboCop
      shell: bash
      run: bundle exec rubocop
