name: Run RSpec
description: Run RSpec tests with PostgreSQL and Redis services
inputs:
  ruby-version:
    description: Ruby version to use
    default: 3.2.0
    required: true
  postgres-password:
    description: Password for PostgreSQL
    required: true
  google-api-key:
    description: Google API Key
    required: true
runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}

    - name: Install dependencies
      shell: bash
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Setup DB and Run Tests
      shell: bash
      env:
        PGHOST: localhost
        PGUSER: postgres
        PGPORT: 5432
        PGPASSWORD: ${{ inputs.postgres-password }}
        REDIS_URL: redis://localhost:6379/1
        GOOGLE_API_KEY: ${{ inputs.google-api-key }}
        RAILS_ENV: test
      run: |
        bin/rails db:create db:migrate db:schema:load
        bundle exec rspec
