name: Run RSpec

on:
  push:
    branches:
      - "*" # Trigger on push to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        # ports:
        #   - 6379:6379
        # options: --entrypoint redis-server --publish 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.0"

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Setup DB, Run tests
        env:
          PGHOST: postgres
          PGUSER: postgres
          PGPORT: ${{ job.services.postgres.ports[5432] }}
          RAILS_ENV: test
        run: |
          bin/rails db:create db:migrate db:schema:load
          bundle exec rspec
