name: Run RSpec

on:
  push:
    branches:
      - "*" # Trigger on push to any branch

jobs:
  rspec:
    runs-on: ubuntu-latest

    if: github.ref != 'refs/heads/main'

    steps:
      - name: Run RSpec
        uses: ./.github/actions/run_rspec
        with:
          ruby-version: "3.2.0"
          postgres-password: ${{ secrets.ROUTE_RATER_DATABASE_PASSWORD }}
          google-api-key: ${{ secrets.GOOGLE_API_KEY }}
