name: RuboCop

on: [push]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    if: github.ref != 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3
      - name: Run RuboCop
        uses: ./.github/actions/rubocop
